# Generated by Django 5.1.4 on 2025-01-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_cart_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
