# Generated by Django 5.1.4 on 2025-01-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
