# Generated by Django 5.1.4 on 2025-01-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_products_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='img',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
